# Docker compose file running on the server
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: taskmanagement
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    # No reason to expose the database outside the docker network
    #ports:
    #  - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskmanagement"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    image: phoolis/task-manage-backend:latest
    environment:
      DB_SYNC: false # Set true for first launch only
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/taskmanagement
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: http://taskmanage.paulcarlson.fi
    restart: always
    healthcheck:
      # node alpine does not have curl installed: use wget instead
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # Docker Autoheal: Monitor and restart unhealthy docker containers.
    labels:
      - autoheal=true
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: phoolis/task-manage-frontend:latest
    ports:
      - "127.0.0.1:8082:80" # host:container
    depends_on:
      - backend
volumes:
  pgdata:
