name: CI
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup repo, node, and dependencies
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install all dependencies
        run: npm run install:all
      - name: Audit npm dependencies
        run: npm audit --audit-level=moderate
      # Linting and testing
      - name: Lint backend
        run: npm run lint:backend
      - name: Test backend
        run: npm run test:backend
      - name: Lint frontend
        run: npm run lint:frontend
      - name: Test frontend
        run: npm run test:frontend
      # Building
      - name: Build backend
        run: npm run build:backend
